server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_drive
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio123

logging:
  level:
    org:
      springframework=DEBUG: DEBUG

external-api:
  authentication-url: http://localhost:8082/login # http://correspondencia.gobernaciondecochabamba.bo/Restserver/singin

  ## Swagger https://springdoc.org/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

  pathsToMatch: /**
